
export const CREATE_RESTURANT_REQUEST="CREATE_RESTURANT_REQUEST";
export const CREATE_RESTURANT_SUCCESS="CREATE_RESTURANT_SUCCESS";
export const CREATE_RESTURANT_FALIURE="CREATE_RESTURANT_FALIURE";

export const GET_ALL_RESTURANT_REQUEST="GET_ALL_RESTURANT_REQUEST";
export const GET_ALL_RESTURANT_SUCCESS="GET_ALL_RESTURANT_SUCCESS";
export const GET_ALL_RESTURANT_FALIURE="GET_ALL_RESTURANT_FALIURE";

export const DELETE_RESTURANT_REQUEST="DELETE_RESTURANT_REQUEST";
export const DELETE_RESTURANT_SUCCESS="DELETE_RESTURANT_SUCCESS";
export const DELETE_RESTURANT_FALIURE="DELETE_RESTURANT_FALIURE";

export const UPDATE_RESTURANT_REQUEST="UPDATE_RESTURANT_REQUEST";
export const UPDATE_RESTURANT_SUCCESS="UPDATE_RESTURANT_SUCCESS";
export const UPDATE_RESTURANT_FALIURE="UPDATE_RESTURANT_FALIURE";

export const GET_RESTURANT_BY_ID_REQUEST="GET_RESTURANT_BY_ID_REQUEST";
export const GET_RESTURANT_BY_ID_SUCCESS="GET_RESTURANT_BY_ID_SUCCESS";
export const GET_RESTURANT_BY_ID_FALIURE="GET_RESTURANT_BY_ID_FALIURE";

export const GET_RESTURANT_BY_USER_ID_REQUEST="GET_RESTURANT_BY_USER_ID_REQUEST";
export const GET_RESTURANT_BY_USER_ID_SUCCESS="GET_RESTURANT_BY_USER_ID_SUCCESS";
export const GET_RESTURANT_BY_USER_ID_FALIURE="GET_RESTURANT_BY_USER_ID_FALIURE";

export const UPDATE_RESTURANT_STATUS_REQUEST="UPDATE_RESTURANT_STATUS_REQUEST";
export const UPDATE_RESTURANT_STATUS_SUCCESS="UPDATE_RESTURANT_STATUS_SUCCESS";
export const UPDATE_RESTURANT_STATUS_FALIURE="UPDATE_RESTURANT_STATUS_FALIURE";

export const CREATE_EVENTS_REQUEST="CREATE_EVENTS_REQUEST";
export const CREATE_EVENTS_SUCCESS="CREATE_EVENTS_SUCCESS";
export const CREATE_EVENTS_FALIURE="CREATE_EVENTS_FALIURE";

export const GET_ALL_EVENTS_REQUEST="GET_ALL_EVENTS_REQUEST";
export const GET_ALL_EVENTS_SUCCESS="GET_ALL_EVENTS_SUCCESS";
export const GET_ALL_EVENTS_FALIURE="GET_ALL_EVENTS_FALIURE";

export const DELETE_EVENTS_REQUEST="DELETE_EVENTS_REQUEST";
export const DELETE_EVENTS_SUCCESS="DELETE_EVENTS_SUCCESS";
export const DELETE_EVENTS_FALIURE="DELETE_EVENTS_FALIURE";

export const GET_RESTURANTS_EVENTS_REQUEST="GET_RESTURANTS_EVENTS_REQUEST";
export const GET_RESTURANTS_EVENTS_SUCCESS="GET_RESTURANTS_EVENTS_SUCCESS";
export const GET_RESTURANTS_EVENTS_FALIURE="GET_RESTURANTS_EVENTS_FALIURE";

export const CREATE_CATEGORY_REQUEST="CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS="CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FALIURE="CREATE_CATEGORY_FALIURE";

export const GET_RESTURANTS_CATEGORY_REQUEST="GET_RESTURANTS_CATEGORY_REQUEST";
export const GET_RESTURANTS_CATEGORY_SUCCESS="GET_RESTURANTS_CATEGORY_SUCCESS";
export const GET_RESTURANTS_CATEGORY_FALIURE="GET_RESTURANTS_CATEGORY_FALIURE";







